import {motion,useReducedMotion} from 'framer-motion'
import {CalendarHeart,ChevronDown,Heart,Instagram as InstagramIcon,MapPin,Send,Clock3,Sparkles} from 'lucide-react'
import {useEffect,useState} from 'react'

const events=[['Mehndi','10 December 2026','5:00 PM onwards','An afternoon of colour, laughter and intricate henna.'],['Sangeet Night','11 December 2026','7:30 PM onwards','An evening of music, dance and family stories.'],['Wedding','12 December 2026','6:30 PM onwards','The sacred vows and the beginning of a beautiful new chapter.']] as const
const venue='The Grand Heritage Resort'

function Countdown(){const target=new Date('2026-12-12T18:30:00+05:30').getTime();const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);const d=Math.max(0,target-now);const a=[['Days',Math.floor(d/86400000)],['Hours',Math.floor(d/3600000)%24],['Minutes',Math.floor(d/60000)%60],['Seconds',Math.floor(d/1000)%60]] as const;return <section className="bg-deepMaroon px-5 py-24 text-ivory"><div className="mx-auto max-w-4xl text-center"><Clock3 className="mx-auto text-gold"/><p className="mt-5 text-[10px] uppercase tracking-[.35em] text-gold">Until we say I do</p><h2 className="mt-4 font-display text-5xl sm:text-6xl">Counting the Moments</h2><div className="mt-10 grid grid-cols-2 gap-px bg-gold/30 sm:grid-cols-4">{a.map(([l,v])=><div key={l} className="bg-deepMaroon p-7"><div className="font-display text-5xl">{String(v).padStart(2,'0')}</div><div className="mt-2 text-[9px] uppercase tracking-[.28em] text-gold">{l}</div></div>)}</div></div></section>}

export default function App(){const reduce=useReducedMotion();const [open,setOpen]=useState(false);const [wish,setWish]=useState('');const [wishes,setWishes]=useState<string[]>(()=>JSON.parse(localStorage.getItem('wishes')||'[]'));const addWish=()=>{if(!wish.trim())return;const n=[wish.trim(),...wishes].slice(0,20);setWishes(n);localStorage.setItem('wishes',JSON.stringify(n));setWish('')};return <main className="overflow-hidden">
<section className="relative min-h-screen overflow-hidden bg-sky-300"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_18%,white_0,transparent_22%),radial-gradient(circle_at_78%_30%,white_0,transparent_18%)] opacity-60"/><div className="relative z-10 flex min-h-screen flex-col items-center justify-center px-6 pb-8 pt-20 text-center text-white"><p className="text-[10px] uppercase tracking-[.4em]">A celebration of love</p><h1 className="mt-5 font-display text-6xl leading-[.9] sm:text-8xl">Agnijeet<br/><span className="font-serif text-4xl italic sm:text-5xl">weds</span><br/>Vaidehi</h1><p className="mt-7 font-serif text-xl">12 December 2026</p><div className="relative mt-12 h-[42vh] w-full max-w-2xl"><motion.div initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:1.1}} className="absolute inset-x-0 bottom-0 h-full bg-contain bg-bottom bg-no-repeat" style={{backgroundImage:"url(https://images.unsplash.com/photo-1583309217182-4d9c2f8d2f11?auto=format&fit=crop&w=1200&q=85)"}}/><div className="absolute inset-x-0 bottom-0 mx-auto h-2/3 w-[80%] bg-gradient-to-t from-sky-300 via-sky-300/40 to-transparent"/></div><a href="#invitation" className="mt-3 flex flex-col items-center gap-2 text-[9px] uppercase tracking-[.3em]"><span>Scroll to explore</span><ChevronDown size={15}/></a></div></section>
<section id="invitation" className="paper-texture bg-ivory px-5 py-24 text-center sm:py-32"><Sparkles className="mx-auto text-gold"/><p className="mt-6 text-[10px] uppercase tracking-[.35em] text-gold">With the blessings of our families</p><h2 className="mt-5 font-display text-6xl text-maroon">You are invited</h2><p className="mx-auto mt-7 max-w-xl text-sm leading-8 text-brown/70">We invite you on this auspicious occasion. Come share the laughter, rituals, music and memories as two families become one.</p><div className="my-10 flex items-center justify-center gap-4"><span className="h-px w-14 bg-gold"/><Heart className="text-gold" size={17} fill="currentColor"/><span className="h-px w-14 bg-gold"/></div><p className="font-display text-4xl text-maroon">Agnijeet & Vaidehi</p></section>
<section className="bg-paper px-5 py-24 text-center"><p className="text-[10px] uppercase tracking-[.35em] text-gold">A day to remember</p><h2 className="mt-4 font-display text-5xl text-maroon">Reveal the Date</h2><button onClick={()=>setOpen(!open)} aria-expanded={open} className="mt-10 inline-flex items-center gap-3 border border-gold px-7 py-4 text-xs uppercase tracking-[.22em] text-maroon">{open?<><CalendarHeart size={17}/>Hide the date</>:<><CalendarHeart size={17}/>Open the invitation</>}</button>{open&&<motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mx-auto mt-10 max-w-xl border-y border-gold/50 py-10"><p className="font-display text-7xl text-maroon">12</p><p className="font-serif text-2xl">December 2026</p><p className="mt-3 text-xs uppercase tracking-[.25em] text-brown/60">Saturday · 6:30 PM onwards</p></motion.div>}</section>
<section className="bg-deepMaroon px-5 py-24 text-ivory"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-[10px] uppercase tracking-[.35em] text-gold">Three chapters of celebration</p><h2 className="mt-4 font-display text-5xl sm:text-6xl">The Celebrations</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{events.map((e,i)=><motion.article whileHover={reduce?{}:{y:-5}} key={e[0]} className="border border-gold/35 bg-[#4B1724]/60 p-8"><span className="text-[10px] uppercase tracking-[.28em] text-gold">0{i+1}</span><h3 className="mt-7 font-display text-4xl">{e[0]}</h3><p className="mt-4 text-xs uppercase tracking-[.18em] text-ivory/60">{e[1]} · {e[2]}</p><p className="mt-7 text-sm leading-7 text-ivory/70">{e[3]}</p></motion.article>)}</div></div></section>
<section className="paper-texture bg-ivory px-5 py-24 sm:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-[10px] uppercase tracking-[.35em] text-gold">Two stories, one home</p><h2 className="mt-4 font-display text-5xl text-maroon sm:text-6xl">The Bride & Groom</h2><p className="mt-7 text-sm leading-8 text-brown/70">Somewhere between ordinary days and unexpected moments, two people found a rhythm that felt like home. Now they are gathering everyone they love to celebrate the beginning of their forever.</p><div className="mt-8 border-l border-gold pl-6"><p className="font-display text-3xl text-maroon">Vaidehi</p><p className="text-xs uppercase tracking-[.2em] text-brown/50">The bride</p><p className="mt-5 font-display text-3xl text-maroon">Agnijeet</p><p className="text-xs uppercase tracking-[.2em] text-brown/50">The groom</p></div></div><div className="aspect-[4/5] bg-[url('https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85')] bg-cover bg-center border border-gold/40"/></div></section>
<section className="bg-maroon px-5 py-24 text-center text-ivory"><InstagramIcon className="mx-auto text-gold"/><p className="mt-6 text-[10px] uppercase tracking-[.35em] text-gold">Share the celebration</p><h2 className="mt-4 font-display text-5xl">#AgnijeetWedsVaidehi</h2><button onClick={()=>navigator.clipboard?.writeText('#AgnijeetWedsVaidehi')} className="mt-8 border border-gold/60 px-6 py-3 text-xs uppercase tracking-[.2em]">Copy hashtag</button></section>
<section className="bg-paper px-5 py-24 text-center"><p className="text-[10px] uppercase tracking-[.35em] text-gold">Before the vows</p><h2 className="mt-4 font-display text-5xl text-maroon">A Little Glimpse</h2><div className="mx-auto mt-12 max-w-5xl overflow-hidden border border-gold/35"><div className="aspect-video"><iframe className="h-full w-full" src="https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0" title="Wedding video" loading="lazy" allowFullScreen/></div></div></section>
<Countdown/>
<section className="paper-texture bg-ivory px-5 py-24"><div className="mx-auto max-w-5xl text-center"><p className="text-[10px] uppercase tracking-[.35em] text-gold">For a graceful evening</p><h2 className="mt-4 font-display text-5xl text-maroon">Things to Know</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[['Venue',venue],['Contact','Family & friends'],['Reminder','Save the date']].map(([a,b])=><article key={a} className="border border-gold/35 bg-paper p-8"><MapPin className="mx-auto text-maroon"/><h3 className="mt-5 font-serif text-2xl text-maroon">{a}</h3><p className="mt-3 text-sm text-brown/65">{b}</p></article>)}</div></div></section>
<section className="bg-paper px-5 py-24"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="text-[10px] uppercase tracking-[.35em] text-gold">Leave a little love</p><h2 className="mt-4 font-display text-5xl text-maroon">Wishes Wall</h2></div><div className="mt-10 flex gap-3"><input value={wish} onChange={e=>setWish(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addWish()} className="min-w-0 flex-1 border-b border-gold bg-transparent px-1 py-3 outline-none" placeholder="Write a blessing for the couple"/><button onClick={addWish} className="bg-maroon px-5 text-white"><Send size={16}/></button></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{wishes.map((w,i)=><article key={i} className="border-l-2 border-gold bg-ivory p-5 font-serif text-maroon">“{w}”</article>)}</div></div></section>
<footer className="paper-texture bg-ivory px-5 py-24 text-center"><p className="text-[10px] uppercase tracking-[.35em] text-gold">Until then</p><h2 className="mt-5 font-display text-6xl text-maroon sm:text-8xl">See you at the mandap</h2><div className="my-9 flex justify-center gap-4"><span className="h-px w-14 bg-gold"/><Heart className="text-gold" fill="currentColor"/><span className="h-px w-14 bg-gold"/></div><p className="font-serif text-xl">12 December 2026</p><p className="mt-2 text-xs uppercase tracking-[.2em] text-brown/55">{venue}</p></footer>
</main>}